### ISSUE TITLE
setup.cmd for windows environment

### ISSUE THREAD

**Issue by sjib** [teksi/district_heating#7]
Please note that we work in a windows environment and I had to copy the setup.sh (for linux environment)  to setup.cmd.
I do not know if this environment must be taken into account for TEKSI users according to the product strategy. 
If not, this would be an advantage.

_Originally posted by @sjib in https://github.com/teksi/distance_heating/issues/1#issuecomment-2110255021_

**Comment by sjib** [comment]
@jpdupuy send windows script

**Comment by jpdupuy** [comment]
The setup_windows.cmd needs some review since I do not know how to convert the 2 following commands :
- PGSERVICE=${PGSERVICE:-pg_tdh}
- DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/..
by
- set DIR=%CD%
- set PGSERVICE=sitecom_edit_dev_service
The setup_windows.cmd uses the setup_windows_sql_script.txt (list of psql scripts to import and execute) in order to call only once PSQL 

[TEKSI_CAD.zip](https://github.com/teksi/district_heating/files/15345534/TEKSI_CAD.zip)

**Comment by sjib** [comment]
`psql -U %user% -p %port% -d %db%  -h %host% -f 060_dss_interlisimport2-halt.sql> 060_2haltuae.log 2>&1`
